POST http://localhost:807/collateral/save
Content-Type: application/json

{
"type" : "car",
  "id": "",
"brand": "Aerobus",
"model": "A300",
"power" : 200,
"year": 2020,
  "values": [{"assessed_Date": "2019-08-22T06:11:00.000Z", "assessed_value": "230000000"}]


}

###