POST http://localhost:807/collateral/save
Content-Type: application/json

{
"type" : "car",
"brand": "Aerobus",
"model": "A300",
"power" : 200,
"year": 2020,
  "carValues": [{"assessedDate": "1019-08-22T06:11:00.000Z", "value": "230000000"},
    {"value": "2300000000", "assessedDate": "1919-08-22T06:11:00.000Z"}]


}

###